name: Bug Report
description: Report a bug to improve Lens
title: "[Bug]: "
body:
  - type: textarea 
    id: summary
    attributes:
      label: General Summary
      description: Please provide a general summary of the problem. If you already have a suggest a possible fix for the bug please write it in detail
      placeholder: e.g. "The main issue is that..."
    validations:
      required: true
    - type: textarea 
    id: current
    attributes:
      label: Current Behavior
      description: Explain what the actual behavior is and how to reproduce it
      placeholder: e.g. "The feature actually does x, y and shows error z."
    validations:
      required: true
  - type: textarea 
    id: expected
    attributes:
      label: Expected Behavior
      description: Explain the behavior expected
      placeholder: e.g. "The feature should do a, then b when you click c."
    validations:
      required: true
