name: Vulnerability Report
description: Report a potential software vulnerability
title: "[Vulnerability]: "
body:
  - type: textarea 
    id: summary
    attributes:
      label: General Summary
      description: Please provide a general summary of the vulnerability
      placeholder: e.g. "An unsafe deserialization vulnerability allows any unauthenticated user to execute arbitrary code on the server."
    validations:
      required: true